apiVersion: apps/v1
kind: Deployment
metadata:
  name: actix-app
  namespace: benchmarking
  labels:
    app: actix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actix-app
  template:
    metadata:
      labels:
        app: actix-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: actix-app
          image: dylanwe/actix-app:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            # Regular scale:
            # requests:
            #   memory: "128Mi"
            #   cpu: "100m"
            # limits:
            #   memory: "256Mi"
            #   cpu: "250m"
            # Vertically scaled:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
--- 
apiVersion: v1
kind: Service
metadata:
  name: actix-service
  namespace: benchmarking
spec:
  type: NodePort
  selector:
      app: actix-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30009
