# create a pod running nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hono-app
  namespace: benchmarking
  labels:
    app: hono-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hono-app
  template:
    metadata:
      labels:
        app: hono-app
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: hono-app
          image: dylanwe/hono-app:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
--- # <-- this is how we seperate resources in the same file
# creating a service for that pod
apiVersion: v1
kind: Service
metadata:
  name: hono-service
  namespace: benchmarking
spec:
  type: NodePort
  selector:
      app: hono-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30008
